# Generated by Django 4.0 on 2022-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(verbose_name='Descripcion de la tarea'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='¿Esta completa?'),
        ),
    ]
